[colors]
background = "#2d2d2d"
foreground = "#d3d0c8"

cursor_fg = "#2d2d2d"
cursor_bg = "#d3d0c8"

ansi = [
    "#2d2d2d",
    "#f2777a",
    "#99cc99",
    "#ffcc66",
    "#6699cc",
    "#cc99cc",
    "#66cccc",
    "#d3d0c8"
]

brights = [
    "#2d2d2d",
    "#f2777a",
    "#99cc99",
    "#ffcc66",
    "#6699cc",
    "#cc99cc",
    "#66cccc",
    "#d3d0c8"
]
